// Flags references to internal AMSI fields or methods
// attackers patch to disable malware scanning. Any hit warrants escalation.
DeviceCustomScriptEvents
| where Timestamp > ago(7d)
| where isnotempty(ScriptContent)
| where ScriptContent has_any ('amsiInitFailed', 'AmsiUtils', 'AmsiScanBuffer', 'amsiContext', 'AmsiSession', 'System.Management.Automation.AmsiUtils')
| project Timestamp, DeviceName, InitiatingProcessFileName, InitiatingProcessAccountName, InitiatingProcessCommandLine, RuleName
| order by Timestamp desc
| take 10000
